name: Get clone count

on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  get_clone_count:
    runs-on: ubuntu-latest

    steps:
    - name: Get clone count
      id: clone_count
      run: |
        curl -H "Authorization: token ${{ secrets.SECRET_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/traffic/clones | jq '.count'
      env:
        SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
        
    - name: Set clone count as a repository metadata
      run: |
        echo "::set-output name=clone_count::${{ steps.clone_count.outputs.clone_count }}"
